import type { Exercise, MuscleGroup, EquipmentId } from './types'
import { EQ } from './seedEquipment'

/**
 * Terse builder so the library below stays readable.
 * `cardio` exercises use repRange as a MINUTES range and log `seconds` per set.
 */
function ex(
  id: string,
  name: string,
  primaryMuscle: MuscleGroup,
  secondaryMuscles: MuscleGroup[],
  equipment: EquipmentId[],
  compound: boolean,
  defaultSets: number,
  repRange: [number, number],
  instructions: string,
  tip?: string,
  extra?: Partial<Exercise>,
): Exercise {
  return {
    id,
    name,
    primaryMuscle,
    secondaryMuscles,
    equipment,
    type: 'strength',
    defaultSets,
    repRange,
    instructions,
    tip,
    compound,
    ...extra,
  }
}

export const SEED_EXERCISES: Exercise[] = [
  // ───────────────────────────── SHOULDERS ─────────────────────────────
  ex(
    'db-shoulder-press',
    'Dumbbell Shoulder Press',
    'shoulders',
    ['triceps', 'core'],
    [EQ.dumbbells, EQ.inclineBench],
    true,
    3,
    [8, 12],
    'Sit upright on an inclined bench with the pad near vertical. Press the dumbbells from ear height to lockout without letting your lower back arch off the pad.',
    'Keep your ribs down — if your back peels off the bench, the weight is too heavy.',
  ),
  ex(
    'db-arnold-press',
    'Arnold Press',
    'shoulders',
    ['triceps'],
    [EQ.dumbbells, EQ.inclineBench],
    true,
    3,
    [8, 12],
    'Start with palms facing you at chin height. Rotate the palms outward as you press overhead, then reverse the path on the way down.',
    'Rotate smoothly through the whole rep rather than twisting at the top.',
  ),
  ex(
    'kb-overhead-press',
    'Kettlebell Overhead Press',
    'shoulders',
    ['triceps', 'core'],
    [EQ.kettlebells],
    true,
    3,
    [6, 10],
    'Rack the kettlebell at your shoulder with the bell resting on your forearm. Press straight up, finishing with your bicep by your ear.',
    'Squeeze your glutes hard — it stops the lower back from taking over.',
    { perSide: true },
  ),
  ex(
    'db-lateral-raise',
    'Dumbbell Lateral Raise',
    'shoulders',
    [],
    [EQ.dumbbells],
    false,
    3,
    [12, 15],
    'Stand tall with a slight forward lean and a soft elbow bend. Raise the dumbbells out to shoulder height, leading with the elbows.',
    'Go light and slow. If you need momentum, drop the weight.',
  ),
  ex(
    'cable-lateral-raise',
    'Cable Lateral Raise',
    'shoulders',
    [],
    [EQ.cable],
    false,
    3,
    [12, 15],
    'Set a single D-handle at the lowest pulley and stand side-on, grabbing it with the far hand across your body. Raise out to shoulder height.',
    'The cable keeps tension at the bottom where dumbbells go slack — pause there for a beat.',
    { perSide: true },
  ),
  ex(
    'cable-face-pull',
    'Cable Face Pull',
    'shoulders',
    ['back'],
    [EQ.cable],
    false,
    3,
    [12, 15],
    'Set the rope at slightly above head height. Pull the rope toward your forehead, splitting your hands apart and driving the elbows high and wide.',
    'Finish every rep with your knuckles facing the ceiling — that is the rear delt doing the work.',
  ),
  ex(
    'db-rear-delt-fly',
    'Dumbbell Rear Delt Fly',
    'shoulders',
    ['back'],
    [EQ.dumbbells, EQ.inclineBench],
    false,
    3,
    [12, 15],
    'Lie chest-down on a bench set to about 30 degrees. With soft elbows, sweep the dumbbells out to the sides until they reach shoulder level.',
    'Think "spread your wings", not "row" — keep the elbows from drifting behind you.',
  ),
  ex(
    'cable-rear-delt-fly',
    'Cable Rear Delt Fly',
    'shoulders',
    ['back'],
    [EQ.cable],
    false,
    3,
    [12, 15],
    'Set both pulleys at shoulder height and cross the cables, taking the left handle in the right hand and vice versa. Pull your arms apart and back.',
    'Keep the arms nearly straight — bending turns this into a row.',
  ),
  ex(
    'cable-front-raise',
    'Cable Front Raise',
    'shoulders',
    [],
    [EQ.cable],
    false,
    3,
    [12, 15],
    'Set the straight bar at the lowest pulley and stand facing away. Raise the bar in front of you to eye level with straight arms.',
    'Stop at eye level — higher just shrugs the traps in.',
  ),
  ex(
    'db-shrug',
    'Dumbbell Shrug',
    'shoulders',
    ['back'],
    [EQ.dumbbells],
    false,
    3,
    [12, 15],
    'Hold heavy dumbbells at your sides. Lift your shoulders straight toward your ears, pause for a count, and lower under control.',
    'Straight up and down — rolling the shoulders adds nothing.',
  ),

  // ───────────────────────────── BICEPS ─────────────────────────────
  ex(
    'db-bicep-curl',
    'Dumbbell Bicep Curl',
    'biceps',
    ['core'],
    [EQ.dumbbells],
    false,
    3,
    [8, 12],
    'Stand with the dumbbells at your sides, palms forward. Curl up while keeping your elbows pinned against your ribs, then lower slowly.',
    'Take three full seconds on the way down — that is where biceps actually grow.',
  ),
  ex(
    'cable-bicep-curl',
    'Cable Bicep Curl',
    'biceps',
    [],
    [EQ.cable],
    false,
    3,
    [10, 12],
    'Attach the straight bar to the lowest pulley and stand a step back from the machine. Curl the bar to chest height with elbows fixed at your sides.',
    'Stepping back puts tension on the biceps at full stretch — do not let the stack touch down between reps.',
  ),
  ex(
    'db-hammer-curl',
    'Hammer Curl',
    'biceps',
    [],
    [EQ.dumbbells],
    false,
    3,
    [10, 12],
    'Hold the dumbbells with palms facing each other and keep that grip the whole way. Curl up to shoulder height without swinging.',
    'This hits the brachialis underneath the bicep — it is what makes the arm look thicker from the side.',
  ),
  ex(
    'kb-hammer-curl',
    'Kettlebell Hammer Curl',
    'biceps',
    [],
    [EQ.kettlebells],
    false,
    3,
    [10, 12],
    'Grip the kettlebell handle with a neutral palm so the bell hangs below. Curl to shoulder height, fighting the bell pulling you forward.',
    'The offset load makes this harder than it looks — start lighter than your dumbbell curl.',
  ),
  ex(
    'cable-hammer-curl',
    'Cable Rope Hammer Curl',
    'biceps',
    [],
    [EQ.cable],
    false,
    3,
    [10, 12],
    'Rope on the lowest pulley, neutral grip on both ends. Curl up and pull the rope ends slightly apart at the top.',
    'Constant tension plus a neutral grip — a great finisher after straight-bar curls.',
  ),
  ex(
    'db-incline-curl',
    'Incline Dumbbell Curl',
    'biceps',
    [],
    [EQ.dumbbells, EQ.inclineBench],
    false,
    3,
    [8, 12],
    'Lie back on a bench set to about 45 degrees and let your arms hang straight down. Curl without letting the elbows drift forward.',
    'The stretched start position is brutal — expect to use less weight than a standing curl.',
  ),
  ex(
    'cable-single-arm-curl',
    'Single-Arm Cable Curl',
    'biceps',
    [],
    [EQ.cable],
    false,
    3,
    [10, 12],
    'Single D-handle on the lowest pulley. Curl one arm at a time with the elbow locked to your side, squeezing hard at the top.',
    'Work your weaker arm first and match its rep count on the strong side.',
    { perSide: true },
  ),
  ex(
    'chin-up',
    'Chin-Up',
    'biceps',
    ['back', 'core'],
    [EQ.pullupGrip, EQ.bodyweight],
    true,
    3,
    [4, 10],
    'Hang from the overhead grip with palms facing you, hands about shoulder width. Pull until your chin clears the bar, then lower all the way down.',
    'If you cannot get full reps yet, jump to the top and lower for 5 seconds.',
  ),

  // ───────────────────────────── TRICEPS ─────────────────────────────
  ex(
    'cable-triceps-pushdown',
    'Cable Triceps Pushdown',
    'triceps',
    [],
    [EQ.cable],
    false,
    3,
    [10, 15],
    'Straight bar at the highest pulley. Tuck your elbows at your sides and press the bar down to full lockout, then let it rise to chest height.',
    'Only the forearms move. If your shoulders are dipping, lighten it.',
  ),
  ex(
    'cable-rope-pushdown',
    'Rope Triceps Pushdown',
    'triceps',
    [],
    [EQ.cable],
    false,
    3,
    [12, 15],
    'Rope at the highest pulley, neutral grip. Push down and split the rope ends apart as you reach lockout.',
    'That outward split at the bottom is what fires the long head — do not skip it.',
  ),
  ex(
    'cable-overhead-triceps',
    'Overhead Cable Triceps Extension',
    'triceps',
    [],
    [EQ.cable],
    false,
    3,
    [10, 15],
    'Rope on a low pulley. Face away, rope behind your head, elbows pointing forward. Extend your arms straight overhead.',
    'The overhead position puts the long head on stretch — the single best triceps builder.',
  ),
  ex(
    'db-skullcrusher',
    'Dumbbell Skullcrusher',
    'triceps',
    [],
    [EQ.dumbbells, EQ.flatBench],
    false,
    3,
    [10, 12],
    'Lie on a flat bench with dumbbells pressed over your chest. Bend at the elbows to lower them beside your ears, then extend back up.',
    'Keep the upper arms angled slightly back toward your head to hold tension at lockout.',
  ),
  ex(
    'db-overhead-triceps',
    'Dumbbell Overhead Triceps Extension',
    'triceps',
    [],
    [EQ.dumbbells],
    false,
    3,
    [10, 12],
    'Hold one dumbbell with both hands overhead. Lower it behind your head by bending only the elbows, then press back to lockout.',
    'Elbows stay narrow and pointed at the ceiling the whole set.',
  ),
  ex(
    'bench-dip',
    'Bench Dip',
    'triceps',
    ['chest', 'shoulders'],
    [EQ.flatBench, EQ.bodyweight],
    true,
    3,
    [10, 15],
    'Hands on the bench edge behind you, legs extended out front. Lower until your upper arms are parallel to the floor, then press back up.',
    'Stay close to the bench — drifting forward dumps the load into your shoulders.',
  ),
  ex(
    'cable-triceps-kickback',
    'Cable Triceps Kickback',
    'triceps',
    [],
    [EQ.cable],
    false,
    3,
    [12, 15],
    'Single D-handle on a low pulley. Hinge forward, upper arm parallel to the floor, and extend the elbow straight back to lockout.',
    'Hold the lockout for a full second each rep.',
    { perSide: true },
  ),

  // ───────────────────────────── CHEST ─────────────────────────────
  ex(
    'db-bench-press',
    'Dumbbell Bench Press',
    'chest',
    ['triceps', 'shoulders'],
    [EQ.dumbbells, EQ.flatBench],
    true,
    4,
    [8, 12],
    'Lie flat with the dumbbells at chest level and elbows about 45 degrees from your torso. Press up and slightly together, then lower under control.',
    'Pinch your shoulder blades into the bench and keep them there all set.',
  ),
  ex(
    'db-incline-press',
    'Incline Dumbbell Press',
    'chest',
    ['shoulders', 'triceps'],
    [EQ.dumbbells, EQ.inclineBench],
    true,
    3,
    [8, 12],
    'Set the bench to about 30 degrees. Press the dumbbells from upper-chest level to lockout above your collarbones.',
    'Higher than 30 degrees and it turns into a shoulder press.',
  ),
  ex(
    'db-chest-fly',
    'Dumbbell Chest Fly',
    'chest',
    [],
    [EQ.dumbbells, EQ.flatBench],
    false,
    3,
    [10, 15],
    'Lie flat holding the dumbbells above your chest with soft elbows. Open your arms wide until you feel a stretch, then hug them back together.',
    'Fixed elbow bend throughout — if the angle changes you are pressing, not flying.',
  ),
  ex(
    'cable-chest-fly',
    'Cable Chest Fly',
    'chest',
    ['shoulders'],
    [EQ.cable],
    false,
    3,
    [12, 15],
    'Both pulleys at chest height with D-handles. Step forward into a split stance and bring your hands together in front of your sternum.',
    'Cross your hands slightly past each other at the end for an extra squeeze.',
  ),
  ex(
    'cable-low-fly',
    'Low-to-High Cable Fly',
    'chest',
    ['shoulders'],
    [EQ.cable],
    false,
    3,
    [12, 15],
    'Both pulleys at the lowest setting. Sweep your hands up and in, finishing together at upper-chest height.',
    'Targets the upper chest — a great pairing with flat dumbbell pressing.',
  ),
  ex(
    'push-up',
    'Push-Up',
    'chest',
    ['triceps', 'core', 'shoulders'],
    [EQ.bodyweight],
    true,
    3,
    [10, 20],
    'Hands slightly wider than shoulders, body in one straight line from head to heels. Lower until your chest nearly touches, then press up.',
    'Squeeze your glutes — it stops the hips sagging and keeps your core working.',
  ),
  ex(
    'db-pullover',
    'Dumbbell Pullover',
    'chest',
    ['back', 'core'],
    [EQ.dumbbells, EQ.flatBench],
    false,
    3,
    [10, 12],
    'Lie flat holding one dumbbell over your chest with both hands. Lower it in an arc behind your head, then pull it back over your chest.',
    'Only go as far back as you can without the ribs flaring up.',
  ),

  // ───────────────────────────── BACK ─────────────────────────────
  ex(
    'cable-lat-pulldown',
    'Cable Lat Pulldown',
    'back',
    ['biceps'],
    [EQ.cable],
    true,
    4,
    [8, 12],
    'Straight bar at the highest pulley, kneel or sit facing the machine. Pull the bar to your upper chest, driving the elbows down and back.',
    'Start each rep by pulling your shoulder blades down, then bend the arms.',
  ),
  ex(
    'pull-up',
    'Pull-Up',
    'back',
    ['biceps', 'core'],
    [EQ.pullupGrip, EQ.bodyweight],
    true,
    3,
    [3, 10],
    'Hang from the overhead grip with palms facing away, hands wider than shoulders. Pull your chest toward the bar, then lower to a full hang.',
    'Dead hang every rep — half reps build half a back.',
  ),
  ex(
    'cable-seated-row',
    'Cable Row',
    'back',
    ['biceps'],
    [EQ.cable],
    true,
    4,
    [8, 12],
    'Both handles or the straight bar at waist height. Sit or stand tall and row to your lower ribs, keeping the elbows close to your body.',
    'Pause for a second with the handle at your ribs before letting it travel back.',
  ),
  ex(
    'cable-single-arm-row',
    'Single-Arm Cable Row',
    'back',
    ['biceps', 'core'],
    [EQ.cable],
    true,
    3,
    [10, 12],
    'One D-handle at waist height. Stagger your stance and row one arm back, letting your torso rotate slightly open at the finish.',
    'The extra rotation reaches lat fibres a two-handed row misses.',
    { perSide: true },
  ),
  ex(
    'db-single-arm-row',
    'Single-Arm Dumbbell Row',
    'back',
    ['biceps', 'core'],
    [EQ.dumbbells, EQ.flatBench],
    true,
    3,
    [8, 12],
    'Place one hand and the same-side knee on the bench with a flat back. Row the dumbbell to your hip, leading with the elbow.',
    'Row toward the hip, not the armpit — that is the lat line of pull.',
    { perSide: true },
  ),
  ex(
    'kb-bent-over-row',
    'Kettlebell Bent-Over Row',
    'back',
    ['biceps'],
    [EQ.kettlebells],
    true,
    3,
    [8, 12],
    'Hinge at the hips to about 45 degrees with a flat back, a kettlebell in each hand. Row both bells to your ribs and lower under control.',
    'If your back rounds at any point, stop the set.',
  ),
  ex(
    'cable-straight-arm-pulldown',
    'Straight-Arm Pulldown',
    'back',
    ['core'],
    [EQ.cable],
    false,
    3,
    [12, 15],
    'Rope at the highest pulley, arms straight out in front. Keeping the elbows locked, sweep the rope down to your thighs.',
    'Pure lat isolation — this is the one that teaches you what a lat contraction feels like.',
  ),

  // ───────────────────────────── LEGS ─────────────────────────────
  ex(
    'kb-goblet-squat',
    'Kettlebell Goblet Squat',
    'legs',
    ['glutes', 'core'],
    [EQ.kettlebells],
    true,
    4,
    [8, 12],
    'Hold a kettlebell at your chest by the horns. Sit straight down between your hips until your thighs pass parallel, then drive up.',
    'The front load keeps your chest up for you — great for grooving squat depth.',
  ),
  ex(
    'db-front-squat',
    'Dumbbell Front Squat',
    'legs',
    ['glutes', 'core'],
    [EQ.dumbbells],
    true,
    4,
    [8, 12],
    'Rest a dumbbell on each shoulder with elbows up. Squat down to depth keeping your torso as upright as you can, then stand.',
    'Elbows high the whole set — when they drop, your chest follows.',
  ),
  ex(
    'db-romanian-deadlift',
    'Dumbbell Romanian Deadlift',
    'legs',
    ['glutes', 'back'],
    [EQ.dumbbells],
    true,
    4,
    [8, 12],
    'Hold the dumbbells in front of your thighs with soft knees. Push your hips straight back, lowering the weights along your legs until you feel the hamstrings stretch.',
    'This is a hip hinge, not a squat — the knees barely move.',
  ),
  ex(
    'kb-swing',
    'Kettlebell Swing',
    'glutes',
    ['legs', 'back', 'core'],
    [EQ.kettlebells],
    true,
    4,
    [12, 20],
    'Hike the bell back between your legs, then snap your hips forward to float it to chest height. Let gravity bring it back down into the next rep.',
    'It is a hip snap, not a front raise — your arms are just rope.',
  ),
  ex(
    'db-bulgarian-split-squat',
    'Bulgarian Split Squat',
    'legs',
    ['glutes', 'core'],
    [EQ.dumbbells, EQ.flatBench],
    true,
    3,
    [8, 12],
    'Place your rear foot on the bench and step the front foot far enough forward to clear your knee. Lower straight down, then drive through the front heel.',
    'The hardest lower-body move you can do with dumbbells. Start bodyweight only.',
    { perSide: true },
  ),
  ex(
    'db-reverse-lunge',
    'Dumbbell Reverse Lunge',
    'legs',
    ['glutes', 'core'],
    [EQ.dumbbells],
    true,
    3,
    [10, 12],
    'Hold the dumbbells at your sides and step one foot back, dropping the back knee toward the floor. Drive through the front heel to return.',
    'Stepping backward is kinder to the knees than lunging forward.',
    { perSide: true },
  ),
  ex(
    'db-step-up',
    'Dumbbell Step-Up',
    'legs',
    ['glutes'],
    [EQ.dumbbells, EQ.flatBench],
    true,
    3,
    [10, 12],
    'Plant one whole foot on the bench and stand up by pushing through that heel. Lower slowly instead of hopping back down.',
    'No pushing off the trailing foot — that leg is just along for the ride.',
    { perSide: true },
  ),
  ex(
    'db-calf-raise',
    'Dumbbell Calf Raise',
    'legs',
    [],
    [EQ.dumbbells],
    false,
    4,
    [15, 20],
    'Hold dumbbells at your sides and rise onto the balls of your feet as high as you can. Pause at the top, then lower all the way down.',
    'A two-second pause at the top beats twice the weight.',
  ),
  ex(
    'cable-pull-through',
    'Cable Pull-Through',
    'glutes',
    ['legs', 'back'],
    [EQ.cable],
    true,
    3,
    [12, 15],
    'Rope on the lowest pulley, face away and straddle the cable with it between your legs. Hinge back, then snap your hips forward to lockout.',
    'Finish with the glutes, not the lower back — the rep ends when your hips are straight.',
  ),
  ex(
    'cable-glute-kickback',
    'Cable Glute Kickback',
    'glutes',
    ['legs'],
    [EQ.cable],
    false,
    3,
    [12, 15],
    'Ankle strap on the lowest pulley. Face the machine, hold on for balance, and drive the working leg straight back and slightly up.',
    'Keep the hips square — let them rotate and the lower back takes the work.',
    { perSide: true },
  ),
  ex(
    'db-hip-thrust',
    'Dumbbell Hip Thrust',
    'glutes',
    ['legs', 'core'],
    [EQ.dumbbells, EQ.flatBench],
    true,
    3,
    [10, 15],
    'Sit with your upper back against the bench and a dumbbell across your hips. Drive your hips up until your torso is parallel to the floor.',
    'Tuck your chin and squeeze the glutes for a full second at the top.',
  ),
  ex(
    'glute-bridge',
    'Glute Bridge',
    'glutes',
    ['legs', 'core'],
    [EQ.bodyweight],
    false,
    3,
    [15, 20],
    'Lie on your back, knees bent and heels close to your hips. Press through the heels to lift your hips into a straight line, then lower.',
    'A great warm-up to wake the glutes up before squats or hinges.',
  ),

  // ───────────────────────────── CORE ─────────────────────────────
  ex(
    'cable-woodchop',
    'Cable Woodchop',
    'core',
    ['shoulders', 'glutes'],
    [EQ.cable],
    true,
    3,
    [10, 12],
    'Single D-handle set high. Stand side-on with both hands on the handle and pull it diagonally across your body down to the opposite hip.',
    'The power comes from rotating your torso, not from pulling with the arms.',
    { perSide: true },
  ),
  ex(
    'cable-crunch',
    'Cable Crunch',
    'core',
    [],
    [EQ.cable],
    false,
    3,
    [12, 20],
    'Kneel facing the machine with the rope at the highest pulley, hands beside your ears. Crunch your ribs down toward your hips.',
    'Curl the spine — if the hips are moving, it is a hip flexor exercise.',
  ),
  ex(
    'hanging-knee-raise',
    'Hanging Knee Raise',
    'core',
    [],
    [EQ.pullupGrip, EQ.bodyweight],
    false,
    3,
    [8, 15],
    'Hang from the overhead grip. Raise your knees toward your chest, tilting the pelvis up at the top, then lower without swinging.',
    'Stop the swing completely between reps, even if it costs you reps.',
  ),
  ex(
    'plank',
    'Plank',
    'core',
    ['shoulders', 'glutes'],
    [EQ.bodyweight],
    false,
    3,
    [30, 60],
    'Forearms under your shoulders, body in one straight line. Brace your abs and squeeze your glutes for the whole hold.',
    'Rep range here is SECONDS. Quality over duration — stop when the hips drop.',
  ),
  ex(
    'db-russian-twist',
    'Dumbbell Russian Twist',
    'core',
    [],
    [EQ.dumbbells],
    false,
    3,
    [12, 20],
    'Sit with knees bent and lean back to about 45 degrees holding one dumbbell. Rotate it from hip to hip, turning your shoulders, not just your arms.',
    'Count a rep each time you reach the same side.',
  ),
  ex(
    'kb-farmer-carry',
    'Kettlebell Farmer Carry',
    'core',
    ['back', 'shoulders', 'legs'],
    [EQ.kettlebells],
    true,
    3,
    [30, 60],
    'Pick up a heavy kettlebell in each hand, stand tall and walk with controlled steps. Rep range here is SECONDS of carry time.',
    'Ribs down, shoulders back. Grip usually fails first — that is the point.',
  ),
  ex(
    'dead-bug',
    'Dead Bug',
    'core',
    [],
    [EQ.bodyweight],
    false,
    3,
    [10, 15],
    'Lie on your back with arms up and knees over hips. Lower one arm and the opposite leg toward the floor, keeping your lower back flat.',
    'If your back arches off the floor, shorten the range.',
  ),
  ex(
    'kb-halo',
    'Kettlebell Halo',
    'core',
    ['shoulders'],
    [EQ.kettlebells],
    false,
    3,
    [8, 12],
    'Hold a kettlebell upside down by the horns at chest height. Circle it around your head, staying close, then reverse direction.',
    'Excellent shoulder warm-up. Alternate directions each rep.',
  ),

  // ───────────────────────────── CARDIO ─────────────────────────────
  ex(
    'row-steady',
    'Rowing — Steady State',
    'fullBody',
    ['back', 'legs', 'core'],
    [EQ.rower],
    true,
    1,
    [15, 30],
    'Row at a conversational pace you could hold for the whole piece. Sequence every stroke legs, then back, then arms.',
    'Rep range here is MINUTES. Aim for a steady stroke rate around 20-24.',
    { type: 'cardio' },
  ),
  ex(
    'row-intervals',
    'Rowing — Intervals',
    'fullBody',
    ['back', 'legs', 'core'],
    [EQ.rower],
    true,
    6,
    [1, 3],
    'Row hard for the interval, then paddle easy for the same time. Keep the drive explosive and the recovery slow.',
    'Rep range here is MINUTES per interval. Log each work interval as a set.',
    { type: 'cardio' },
  ),
]
